renaissance-benchmarks/renaissance

README.md, build.sbt, renaissance-core/src/main/java/org/renaissance/MetaInfo.java, renaissance-harness/src/main/scala/org/renaissance/renaissance-suite.scala
Currently, there are plenty of spaces where version information is kept. This PR tries to at least keep in sync version printed by harness and version as determined by the main.sbt.
I am not sure this is the cleanest solution but we have to somehow keep the individual places in sync.
Btw, it also means that the released JARs contain invalid version :-(.
=> Keep version at one place only

renaissance-core/src/main/java/org/renaissance/MetaInfo.java
Seems that https://bugs.openjdk.java.net/browse/JDK-8201636 was really the root cause.
@villazon Would you, please, check that this fixed #123 for you too? Thanks!
=> Fix #123 (manifest reading bug on JDK8)

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/PageRank.scala
Using `scala.collection.immutable.StringOps` should fix issue #127
=> fix jdk11 compilation error due to Java String API change

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala
Fixes #66
Set `mxRetries` back to 16.
=> Explicitly bind Spark to localhost

benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleChirper.scala
This PR implements the comments by @vkostyukov in issue #106 (see https://github.com/renaissance-benchmarks/renaissance/issues/106#issuecomment-492048351). 
Since the crash mentioned in #106 never occurred on the machines at my disposal, additional testing would be helpful. In case the crash still occurs, we can leave this PR open until a proper fix is implemented.
=> Fix finagle-chirper

benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala
This caused silent failures when run on Windows.
=> Dotty: use OS-specific path separator

benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleHttp.scala
finagle-http is now sending requests in parallel. Also, the measured part of the benchmark now excludes starting of the threads (there is a barrier to start all the work at once).
Note that the parameters (number of clients and number of requests) were changed to roughly correspond to the previous performance (same order of magnitude).
Also note that this commit changes the performance of the finagle-http benchmark drastically.
This closes #148 and #149 but there still seems to be some other bug as sometimes exactly one request is lost (see Travis links in #151).
=> finagle-http bugfixes (fixes #148, fixes #149)

benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleChirper.scala
This solves #164. Throughput is fairly close to the previous version, but seems to be slightly better on all VMs I tested.
=> Fix for finagle-chirper locking problem

.travis.yml
After this change, we compile & run on (`java -version`):
```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```
=> Travis: switch to OpenJDK for Java 11 (fixes #167)

build.sbt, project/plugins.sbt, renaissance-harness/src/main/scala/org/renaissance/renaissance-suite.scala
Adds `sbt-git` plugin to retrieve Git revision hash and date and stores it into `MANIFEST.MF`. Quite useful when you run several experiments and you want to check which revision you actually used.
It also embeds this information into the JSON output.
After these changes, `MANIFEST-MF` contains also following information:
```ini
Git-Head-Commit: hash-of-the-commit
Git-Head-Commit-Date: 2019-07-04T16:06:00+0200
Git-Uncommitted-Changes: true
```
And the JSON is extended with this fragment:
```json
"suite": {
"name": "Renaissance Benchmark Suite",
"git": {
"commit_hash": "0767866594a84584aa0e1e3859ac0344c86436bf",
"dirty": "true",
"commit_date": "2019-07-10T11:02:56+0200"
},
"version": "0.10.0"
}
```
=> Add Git revision information

.travis.yml
This should fix #43 where non-ASCII characters caused compilation problems on Mac.
=> Travis: check *.java are in pure ASCII

.travis.yml, tools/check-encoding.sh
Seems that Travis is not able to parse such easy command as `! grep -P -nH -r '--include=*.java' -e '[^\x00-\x7F]' .` ;-).
Opening this PR to ensure we run Travis again.
=> Fix broken Travis

.travis.yml, README.md, benchmarks/dummy/src/main/java/org/renaissance/dummy/DummyEmpty.java, benchmarks/dummy/src/main/java/org/renaissance/dummy/DummyFailing.java, benchmarks/dummy/src/main/java/org/renaissance/dummy/DummySetupFailing.java, benchmarks/dummy/src/main/java/org/renaissance/dummy/DummyTeardownFailing.java, benchmarks/dummy/src/main/java/org/renaissance/dummy/DummyValidationFailing.java, renaissance-core/src/main/java/org/renaissance/RenaissanceBenchmark.java, renaissance-core/src/main/java/org/renaissance/ResultObserver.java, renaissance-harness/src/main/scala/org/renaissance/renaissance-suite.scala
This is an attempt to fix #162 (JSON and CSV do not report in any way whether the benchmark failed).
In this PR the information about benchmark outcome is added to JSON. I have not added it to CSV as I see no reasonable way to store it there.
For the purposes of testing, this PR also extends the dummy benchmarks with two failing ones.
The downside is that the code for the output writers is growing in complexity. Hopefully with #81 this functionality could be moved to separate plugins.
=> Store benchmark failure into JSON (issue #162)

renaissance-harness/src/main/scala/org/renaissance/harness/RenaissanceSuite.scala
This is to improve output stability/repeatability across different environments. For example, even simple `%8.5f` can change based on user/OS settings.
This is most important for validation where hashes are computed but it also makes any output diffing simpler in general (noticed because of PR #197).
=> Reset locale to Locale.ROOT

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/PageRank.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/ZipResourceUtil.scala
This was triggered by @davleopo mentioning leftover code in `page-rank` in the API cleanup PR :-)
When making sure that it was indeed just leftover code, I realized that maybe the setup code is causing more disk IO than necessary, so I modified the code to get rid of it.
The code originally read the whole zipped file as a single String into memory, optionally reduced the number of lines (for the `test` configuration), and wrote it uncompressed to disk. Then it used the the `SparkContext.textFile()` method to create an RDD which was then processed into a map and cached.
This uses a lazy `Source` to read either all (or a subset of) lines from the zipped file into a collection, and uses the `SparkContext.parallelize()` method to create an RDD which is then processed the same way as above. It …
=> Avoid unnecessary disk IO and add hash-based validation in page-rank

project/jmh.scala, renaissance-jmh/src/main/java/org/renaissance/jmh/JmhRenaissanceBenchmark.java
Switch  @BenchmarkMode to Mode.SingleShotTime and remove unneeded timing parameters from @Warmup and @Measurement as a result of that.
=> Issue #185 - Use SingleShotTime in JMH wrappers

website/_layouts/base.html
This is the second part of the solution for the website issue.
Before:
After:
=> Add the new CSS class to the layout

CONTRIBUTION.md, README.md, renaissance-core/src/main/java/org/renaissance/Plugin.java, renaissance-harness/src/main/java/org/renaissance/harness/EventDispatcher.java, renaissance-harness/src/main/java/org/renaissance/harness/ExecutionDriver.java, renaissance-harness/src/main/java/org/renaissance/harness/ExecutionPlugins.java, renaissance-harness/src/main/java/org/renaissance/harness/ExecutionPolicies.java, renaissance-harness/src/main/scala/org/renaissance/harness/Config.scala, renaissance-harness/src/main/scala/org/renaissance/harness/ConfigParser.scala, renaissance-harness/src/main/scala/org/renaissance/harness/MarkdownGenerator.scala, renaissance-harness/src/main/scala/org/renaissance/harness/RenaissanceSuite.scala, renaissance-harness/src/main/scala/org/renaissance/harness/ResultWriter.scala
This provides initial support for forced GC mentioned in #193.
The CLI provides a `--force-gc <when>` option which allows specifying `before`, `after` or `around` in place of `<where>`. The option can be used multiple times, so using `--force-gc before` and `--force-gc after` at the same time has cumulative effect. 
While this is a simple feature, there are a couple of things that should be decided explicitly and which may trigger some other changes -- feedback is therefore welcome.
It is internally implemented as a built-in, lowest-priority plugin (executes first/last in paired notifications) hooked either into the `afterOperationSetUp` (i.e. before operation) or the `beforeOperationTearDown` (i.e. after operation) notification slots. It is also inside the unix-timestamped phase covering …
=> WiP: Force GC before measured operation by default

.travis.yml
By default, MacOS on Travis now uses JDK 13 which fails the build (because of SBT, probably). So let's use JDK 9 for now there.
=> Travis: force older JDK on MacOS

benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleHttp.scala
The `finagle-http` benchmark creates a new (anonymous) response handler for each HTTP request, eventually creating thousands (`$requestCount$`) of them in the benchmark loop. This has been pointed out in _Detection of Suspicious Time Windows in Memory Monitoring_ by Markus Weninger et al. published at MPLR'19, see https://dx.doi.org/10.1145/3357390.3361025
This has been on the back burner for some time (I forgot about it), but I would generally consider creating such instances in a loop a bad practice, so the code in this PR manually hoists the response handler creation out of the loop and uses just one handler for all HTTP requests.
However, I'm also willing to accept an argument (if anyone is willing to play the devil's advocate) that it's either a non-problem or that a normal …
=> Avoid creating thousands of response handler objects in finagle-http

plugins/ubench-agent/.gitignore, plugins/ubench-agent/build-ubench-agent.sh, plugins/ubench-agent/build.sbt, plugins/ubench-agent/lib/.gitignore, plugins/ubench-agent/project/build.properties, plugins/ubench-agent/project/plugins.sbt, plugins/ubench-agent/src/main/java/org/renaissance/plugins/ubenchagent/Main.java
This PR adds a new plugin to enable measurement of hardware counters via [ubench-agent](https://github.com/D-iii-S/java-ubench-agent). The code was originally mentioned in #191.
The plugin is compiled via SBT but user has to first compile the C agent.
After that, following spell runs Renaissance and collects L1 cache misses and wall-clock time.
```shell
java \
-agentpath:plugins/ubench-agent/libubench-agent.so \
-jar target/renaissance-gpl-0.10.0.jar \
--csv output.csv  --json output.json \
--plugin 'plugins/ubench-agent/target/plugin-ubenchagent-assembly-0.0.1.jar!org.renaissance.plugins.ubenchagent.Main' \
--with-arg SYS:wallclock-time,PAPI_L1_DCM \
finagle-http -r 50
```
There are few things to decide/discuss.
* Do we want the plugins in the same repository? Personally, I would prefer …
=> ubench-agent plugin [WiP]

renaissance-harness/src/main/java/org/renaissance/harness/ExecutionDriver.java, renaissance-harness/src/main/scala/org/renaissance/harness/RenaissanceSuite.scala, renaissance-harness/src/main/scala/org/renaissance/harness/ResultWriter.scala
This adds VM uptime timestamps (in nanoseconds) to the start of measured operations, as discussed in #107. To determine the value of `nanoTime()` at VM start, we use the average of two `nanoTime()` readings straddling two distinct but consecutive `currentTimeMillis()` values so that we get somewhere in the middle of the platforms `currentTimeMillis()` accuracy. 
Because this changes the version of the JSON output format, I also bundled changes which add much more info about the environment to the JSON output file (basically everything there is that you get in the `VM Summary` tab of `jconsole`). While the information is not going to be used most of the time, it does provide a more colorful picture of the VM the results were collected on (which GC, which compilation system, etc) which is …
=> Add VM uptime timestamps to repetitions and (much) more environmental info

benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleChirper.scala
This shall fix #211 (finagle-chirper fails on x86-64 Windows).
=> finagle-chirper: fix resource path creation

benchmarks/neo4j/build.sbt, benchmarks/neo4j/project/build.properties, benchmarks/neo4j/src/main/scala/org/renaissance/neo4j/Neo4jAnalytics.scala, benchmarks/neo4j/src/main/scala/org/renaissance/neo4j/analytics/AnalyticsBenchmark.scala
Replaces PR #212.
Contains :
- added index/constraints
- wait for constraints to be online
- improved some of the cypher statements
- switched to parameter usage
- upgrade to Neo4j 3.5.12
- configure page-cache
- benchmark validation
=> Updates to Neo4j benchmark

website/_layouts/mainrenaissance.html, website/resources/styles/proj.css
Website update to show the latest numbers from https://github.com/renaissance-benchmarks/measurements/pull/4/
Each JDK is shown in a different tab, making it future proof.
This assumes that, once the above PR will be merged, the JDK 8 and JDK 11 charts will be available at location : 
- https://github.com/renaissance-benchmarks/measurements/raw/master/stripe-jdk-8.png
- https://github.com/renaissance-benchmarks/measurements/raw/master/stripe-jdk-11.png
=> Add JDK8 and JDK11 charts on the main page

.travis.yml, renaissance-core/src/main/java/org/renaissance/core/BenchmarkRegistry.java, renaissance-harness/src/main/scala/org/renaissance/harness/RenaissanceSuite.scala
Removes `dummy` benchmarks and groups from the output of the `--list`, `--raw-list`, and `--group-list` CLI commands to remove the need to filter out these in scripts. This fixes #220. 
This is consistent with the fact that dummy benchmarks are ignored when the user requests to run `all` benchmarks, where `all` is considered to be a special group containing all (public) benchmarks.
I'm not so sure if this is the right behavior for the `--list` command, which is not usually consumed by scripts, but my OCD was happier when I filtered it everywhere :-)
This does not affect the list in `README.md`, where these dummy benchmarks/groups are still listed.
=> Don't include dummy benchmarks/groups in output of CLI list commands

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/Als.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/ChiSquare.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/DecTree.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/GaussMix.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/MovieLens.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/NaiveBayes.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/PageRank.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala
This fixes #226 .
Moreover, since we don't really have unit tests, I've added a `checkCaching` method to the `SparkUtil` trait. That way we can explicitly mark some RDDs that need to be cached and fail otherwise. That will make things explicit and avoid such problems in the future.
Before I start porting this extra check to all Spark benchmarks that use RDDs, please let me know if you think this idea makes sense (or if you see a better way to achieve the same thing).
=> Address RDD caching problems

build.sbt
Instead of failing the build, this stores `"unknown"` as the Git revision the JAR was built from.
=> Allow missing .git folder (fixes #234)

renaissance-harness/src/main/scala/org/renaissance/harness/ResultWriter.scala
The intent is to collect additional information on systems that support it and do nothing on other systems. The missing match instead caused a MatchError on non-Unix systems.
Should fix #236
=> Add missing default case to OS-type match in ResultWriter

build.sbt
=> Add out of the box support for spark benchmarks on JDK16

renaissance-jmh/src/main/java/org/renaissance/jmh/JmhRenaissanceBenchmark.java, tools/ci/bench-jmh.sh, tools/renaissance-jmh.sh, tools/renaissance.sh
This modifies the JMH wrapper to be able to use other configurations, changes the CI script that runs the JMH bundle to use the `test` configuration, and ensures that we pass the right JVM arguments to the JMH-forked VM.  These are relatively small changes on top of `master`, not a long-running branch (what #255 should have been but wasn't). And yes, it also tacks on two convenience scripts to run the current build of Renaissance and the JMH bundle, which is useful during development.
=> Use test configuration in CI runs of the JMH bundle (and add convenience scripts)

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/Als.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/ChiSquare.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/DecTree.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/GaussMix.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/MovieLens.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/NaiveBayes.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/PageRank.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/ResourceUtil.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala, renaissance-core/src/main/java/org/renaissance/BenchmarkParameter.java, renaissance-core/src/main/java/org/renaissance/core/BenchmarkInfo.java
This was originally intended as a simple follow-up to #246 (making actual use of the scratch directory), but I ended up reorganizing the code around a common pattern so that the benchmarks all look alike. The following benchmarks are being updated:
- Avoid relying on method side-effects in the code responsible for preparing the input datasets.
- The benchmark setup code now follows a common pattern in which `prepareInput()`, `loadData()` and `ensureCached()` methods return values that need to be passed around.
- This makes the data flow more explicit and easier to follow, in addition to clearly separating preparation and loading.
- Use more (very) prominent names for the fields representing computation inputs and outputs.
- Get rid of unnecessary state held between benchmark method calls. …
=> Clean up apache-spark benchmarks

benchmarks/actors-akka/build.sbt, benchmarks/database/build.sbt, benchmarks/jdk-concurrent/build.sbt, benchmarks/jdk-streams/build.sbt, benchmarks/rx/build.sbt, benchmarks/scala-dotty/build.sbt, benchmarks/scala-sat/build.sbt, benchmarks/scala-stdlib/build.sbt, renaissance-harness/build.sbt
Scala 3 (Dotty compiler) got released last Friday in its final version.
The Scala 2 version with the matching Tasty reader got released today: 2.13.6.
This means that we won't face this https://github.com/scala/bug/issues/12374 nor https://github.com/lampepfl/dotty/issues/4192 anymore.
The benchmarks works as expected with the new version:
```
====== dotty (scala-dotty) [default], iteration 0 started ======
GC before operation: completed in 9.822 ms, heap usage 19.181 MB -> 4.119 MB.
WARNING: This benchmark provides no result that can be validated.
There is no way to check that no silent failure occurred.
====== dotty (scala-dotty) [default], iteration 0 completed (5541.862 ms) ======
====== dotty (scala-dotty) [default], iteration 1 started ======
GC before operation: completed in 42.440 …
```
=> Update dotty to final version and its scala version to 2.13.6

benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleChirper.scala
Otherwise, reading of the `new-years-resolution.csv` will fail on systems where UTF-8 is not the default charset.
=> finagle-chirper: read with UTF-8 explicitly

benchmarks/actors-akka/build.sbt, benchmarks/actors-reactors/build.sbt, benchmarks/apache-spark/build.sbt, benchmarks/database/build.sbt, benchmarks/dummy/build.sbt, benchmarks/jdk-concurrent/build.sbt, benchmarks/jdk-streams/build.sbt, benchmarks/neo4j/build.sbt, benchmarks/rx/build.sbt, benchmarks/scala-dotty/build.sbt, benchmarks/scala-sat/build.sbt, benchmarks/scala-stdlib/build.sbt, benchmarks/scala-stm/build.sbt, benchmarks/scala-stm/scala-stm-library/build.sbt, benchmarks/twitter-finagle/build.sbt, build.sbt, plugins/jmx-timers/project/plugins.sbt, plugins/ubench-agent/project/plugins.sbt, project/build.scala, project/jmh.scala, project/plugins.sbt, renaissance-harness/build.sbt
This does several things in an attempt to streamline the build process:
- Marks dependency on `renaissance-core` in other modules as `provided`.  This is a dependency that is expected to be provided by the *runtime*, which is exactly what we do. As a result, the `renaissance-core` JAR file is excluded from the runtime dependencies of other modules and is not repeatedly copied into the final bundle.
- Dismantles the `projectJars` and `jarsAndListGenerator` tasks which together did too many things into separate tasks responsible for generating the `modules.properties` and `benchmarks.properties` files and for copying the runtime dependencies into the `resource_managed` directory of the root project. 
- Factors the inline definition of the task to generate JMH wrappers out of the …
=> Make build.sbt (and friends) a bit easier to understand

benchmarks/apache-spark/build.sbt, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala
Also updates the expected size of the `winutils.exe` binary which I forgot to do when I last updated it. This should help #265 but apparently, there is a bit more going on.
=> Update Spark to 3.1.2

benchmarks/dummy/src/main/java/org/renaissance/dummy/DummyEmpty.java
The new parameter handling code now complains (failing the benchmark) if we ask for a non-existing configuration. This can fail the CI builds because the `dummy-empty` benchmark is used to replace incompatible benchmarks in JMH runs and I forgot to add the `test` configuration.
Fixes #268
=> Add empty "test" configuration to the dummy-empty benchmark

README.md, benchmarks/actors-akka/src/main/scala/org/renaissance/actors/AkkaUct.scala, benchmarks/actors-reactors/src/main/scala/org/renaissance/actors/Reactors.scala, benchmarks/jdk-concurrent/src/main/scala/org/renaissance/jdk/concurrent/FjKmeans.scala, benchmarks/jdk-concurrent/src/main/scala/org/renaissance/jdk/concurrent/FutureGenetic.scala, benchmarks/jdk-streams/src/main/scala/org/renaissance/jdk/streams/Mnemonics.scala, benchmarks/jdk-streams/src/main/scala/org/renaissance/jdk/streams/ParMnemonics.scala, benchmarks/jdk-streams/src/main/scala/org/renaissance/jdk/streams/Scrabble.scala, benchmarks/neo4j/src/main/scala/org/renaissance/neo4j/Neo4jAnalytics.scala, benchmarks/rx/src/main/scala/org/renaissance/rx/RxScrabble.scala, benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala, benchmarks/scala-sat/src/main/scala/org.renaissance.scala.sat/ScalaDoku.scala, benchmarks/scala-stdlib/src/main/scala/org/renaissance/scala/stdlib/ScalaKmeans.scala, benchmarks/scala-stm/src/main/scala/org/renaissance/scala/stm/Philosophers.scala, benchmarks/scala-stm/src/main/scala/org/renaissance/scala/stm/ScalaStmBench7.scala, benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleChirper.scala, benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleHttp.scala, renaissance-core/src/main/java/org/renaissance/core/BenchmarkDescriptor.java, renaissance-core/src/main/java/org/renaissance/core/BenchmarkSuite.java, renaissance-harness/src/main/java/org/renaissance/harness/ExecutionDriver.java
For now, we retain the original groups that mostly correspond to benchmark modules, so that we don't break scripts that might have been using them. We also display the primary group in benchmark output (instead of benchmark module), which I believe we always intended, but there was no need to differentiate between benchmark module and benchmark group back then.
=> Make the benchmark primary groups more user-friendly

.github/workflows/build.yml, tools/ci/bench-show-env.sh, tools/ci/common.sh, tools/ci/pre-show-env.sh
This PR enables use of GitHub Actions for CI. (Cleaned-up version of the `issue/243` branch. Travis CI will be removed as part of another PR.)
Current status:
* Checks (encoding, formatting) ... ok.
* Linux builds (and runs): JDK 8, 9, 10, 11, Openj9 on JDK 8 and 11 ... ok (ignoring spurious failures of the build servers).
* Linux builds (and runs): JDK 12+ .. failing.
* MacOS builds (and runs): JDK 8 and 11 ... ok.
* Windows builds (and runs): failing (see #265).
This is a base version, we can later switch to a more complex workflow.
GHA also allows for artifacts but the pricing is not clear to me at the moment (i.e., no artifacts are stored at this moment).
To decide before merge:
* Remove the JDK12+ builds at the moment (they fail because of db-shootout)? I hope I will fix the Windows …
=> Enable GitHub Actions

build.sbt, renaissance-core/src/main/java/org/renaissance/core/ModuleLoader.java
The family of `getResource` functions requires [Unix-style paths](https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#getResource-java.lang.String-).
The filenames are sane here so this trivial fix should work but perhaps @lbulej could confirm that it will not break something else. Thanks!
=> Attempted fix for #272 (broken Windows builds)

benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala
This fixes the validation on Windows where the sorting was case insensitive.
=> dotty validation: force C-locale ordering

.github/workflows/build.yml
It is not perfect as the helper shell scripts are not used -- as on Linux and MacOS -- but they fail without any hint why (it seems to me that it is related to the SBT server/client feature but that is only a guess).
It would be nice to have it more Windows-only -- i.e. use `.bat` instead of Bash scripts --  but that can be changed later. I would like to have it in `master` ASAP to catch issues on Windows earlier. At the moment, it compiles and runs on Windows without any issues (up to JDK 11).
=> GitHub Actions: run on Windows too

README.md, benchmarks/database/src/main/scala/org/renaissance/database/DbShootout.scala
This is to avoid out-of-the-box crashes on JVM 12 before we can resolve issue #163.
=> Temporarily limit supported JVM in 'dbshootout' to version 11

benchmarks/actors-reactors/build.sbt, benchmarks/apache-spark/build.sbt, benchmarks/neo4j/build.sbt, benchmarks/scala-stm/build.sbt, benchmarks/scala-stm/scala-stm-library/build.sbt, benchmarks/scala-stm/scala-stm-library/dep_tests/sbt/build.sbt, benchmarks/twitter-finagle/build.sbt
Scala 2.12.14 was released at the end of May and I think we can afford to be up-to-date here.
=> Bump Scala 2.12 version to 2.12.14

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/Als.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/AlsMl.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/ChiSquare.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/DecTree.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/GaussMix.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/NaiveBayes.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala
Most (but not all) Spark benchmarks dump the result of the last benchmark operation to disk during benchmark tear-down. This is primarily useful for development, but it's not necessarily something we should do all the time (or by default).
In addition, the current implementation throws a `NullPointerException` in the tear-down phase if the benchmark fails during the first operation (because the operation result will be uninitialized), which ends up masking the exception thrown from the failed benchmark operation.
=> Add a missing null check and make dumping of Spark benchmark results optional (and disabled by default)

renaissance-core/src/main/java/org/renaissance/BenchmarkResult.java, renaissance-harness/src/main/java/org/renaissance/harness/ExecutionDriver.java
This gives us a chance to at least print the name of the failure exception, because the exception can be lost if any of the tear-down methods in the *finally* blocks throws an exception.
This can actually occur in some of the Spark benchmarks because they try to dump the result of the last operation but do not expect the very first operation to fail. This assumption has been proven wrong #283 and losing the original exception makes things a bit more confusing. A fix for that is in #288.
An alternative would be to complicate the exception handling to make sure the original exception does not get lost even though the benchmark is already doomed at that point.
=> Print a message if the benchmark operation fails

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/Als.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/AlsMl.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/ChiSquare.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/DecTree.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/GaussMix.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/MovieLens.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/PageRank.scala
The limits reflect the recommendations from #260, with the limits for `gauss-mix`, `chi-square` and `dec-tree` bumped up by 2 threads (providing a bit of slack that does not help but should not hurt), resulting in the following defaults for the `spark_thread_limit` parameter:
- 4 in `chi-square` and `gauss-mix`
- 6 in `dec-tree`
- 8 in `movie-lens`
- 12 in `als`, `als-ml`, `log-regression` and `page-rank`
- unlimited in `naive-bayes`
=> Set benchmark-specific thread limits for the Spark local executor

renaissance-harness/src/main/scala/org/renaissance/harness/ResultWriter.scala
There is a `java.vm.compressedOopsMode` system property on newer JVMs (found it on OpenJDK 11, but not on OpenJDK 8) which provides information about the compressed OOPs mode (either `Zero based` or `Non-zero disjoint base`) **if** used by the JVM. This is a useful bit of information to store in the benchmark result.
On older JVMs (JDK8), the property is unset even though the JVM uses compressed OOPs. There does not seem to be a reasonable way  (e.g., an MXBean) to find out *if and what mode the JVM uses*, so we just have to assume that it is used for heaps <= 32G (unless disabled using the `-XX:-UseCompressedOops` option).
On newer JVMs that support the property, e.g., JDK11, the property will be unset when the JVM does not use compressed OOPs. This was tested using the …
=> Report compressed OOPs mode

.github/workflows/build.yml, tools/ci/bench-jmh.sh, tools/ci/common.sh
Added more environments to be tested on GitHub Actions CI.
It now runs on
* Linux: all JDKs from 8 to 16
* Linux with OpenJ9: 8, 11, 16
* MacOS: 8, 11, 13, 15
* Windows: 8, 11, 13, 15
Also added `--add-opens` to JMH runs for JDK 16 (see #241).
=> CI: test on more JDKs

README.md, plugins/jmx-timers/build.sbt, plugins/ubench-agent/build.sbt, renaissance-core/src/main/java/org/renaissance/core/BenchmarkSuite.java, renaissance-core/src/main/java/org/renaissance/core/ModuleLoader.java, renaissance-harness/src/main/scala/org/renaissance/harness/ConfigParser.scala, renaissance-harness/src/main/scala/org/renaissance/harness/MarkdownGenerator.scala, renaissance-harness/src/main/scala/org/renaissance/harness/RenaissanceSuite.scala, tools/ci/bench-plugins.sh
Add `Renaissance-Plugin` property to a `MANIFEST.MF` of a plugin describing plugin main class. When the plugin is loaded, the class is automatically read from the manifest. Simplifies the command line, fixes #194.
=> Specify plugin class inside plugin JAR

benchmarks/actors-reactors/build.sbt, benchmarks/apache-spark/build.sbt, benchmarks/neo4j/build.sbt, benchmarks/scala-stm/build.sbt, benchmarks/scala-stm/scala-stm-library/build.sbt, benchmarks/scala-stm/scala-stm-library/dep_tests/sbt/build.sbt, benchmarks/twitter-finagle/build.sbt
Scala 2.12.15 landed -> https://github.com/scala/scala-dev/issues/783
So we can bump our 2.12.14 dependencies and do a renaissance 0.13.0 release which will officially support the now released JDK17.
=> Update from scala 2.12.14 to 2.12.15 for complete JDK17 compatibility

CONTRIBUTING.md, README.md, documentation/README.md, documentation/adding-benchmark.md, documentation/design.md, documentation/ide.md, documentation/jar-bundle.md, documentation/plugins.md, plugins/jmx-timers/README.md, plugins/ubench-agent/README.md, renaissance-harness/src/main/scala/org/renaissance/harness/MarkdownGenerator.scala, tools/ci/check-markdown.sh, tools/pre-push
Various bits of missing documentation (not ready for merging, opening PR to track progress).
I was also wondering whether not to split a bit more README.md and CONTRIBUTING.md. The README now is quite long and mixes things for users as well as for developers. I would rather have the README shorter with instructions on how to run it (assuming the user downloaded a release) and keep separate documents for building and about the design.
=> Documentation improvements

tools/ci/common.sh, tools/pre-push, tools/renaissance-jmh.sh, tools/renaissance.sh
This seems to be needed because the command (as used in various scripts) suddenly started returning commit id with one extra
character, resulting in a mismatch between `git describe` and the git-described version produced by the `sbt-git` plugin (at least on my machine with git 2.31.1). Due to this, the pre-push readme check fails to find the right JAR and aborts the push.
=> Set length of abbreviated commit id in git describe

.github/workflows/build.yml, tools/ci/common.sh
Follow-up to PR #297.
JDK17 for Mac and Windows is not yet available, tracked here: actions/setup-java#229
=> CI: test on JDK17

tools/ci/common.sh, tools/pre-push, tools/renaissance-jmh.sh, tools/renaissance.sh, website/_posts/2021-07-07-renaissance-0-12-0.md, website/_posts/2021-09-16-renaissance-0-13-0.md
There is also a draft of GitHub release (shorter) that you should be able to see. If we are fine with this, I'll go ahead with the release.
Note: this is built on top of #299 so that I can push to GitHub.
=> Add release notes for the upcoming v0.13.0

renaissance-harness/src/main/scala/org/renaissance/harness/ResultWriter.scala
Substrate VM does not support some of the system info queries we do when dumping JSON.
```
SEVERE: Harness failed with com.oracle.svm.core.jdk.UnsupportedFeatureError: OperatingSystemMXBean methods
at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
at com.oracle.svm.core.jdk.management.SubstrateOperatingSystemMXBean.getFreePhysicalMemorySize(SubstrateOperatingSystemMXBean.java:107)
at org.renaissance.harness.JsonWriter.getOsInfo(ResultWriter.scala:184)
at org.renaissance.harness.JsonWriter.getEnvironment(ResultWriter.scala:164)
at org.renaissance.harness.JsonWriter.store(ResultWriter.scala:363)
at org.renaissance.harness.ResultWriter.org$renaissance$harness$ResultWriter$$storeResults(ResultWriter.scala:63)
at …
```
=> Make system info dump more resilient

benchmarks/database/build.sbt, benchmarks/neo4j/build.sbt, benchmarks/scala-dotty/build.sbt
This was primarily triggered by the issues with `db-shootout` on less common CPU/platform combinations (see #153 and #296) and at least part of the cause is that [JNA](https://github.com/java-native-access/jna) version (4.2.1) used in `db-shootout` simply does not support those combinations. So this forces JNA in `db-shotout` to version 5.9.0 ([latest](https://github.com/java-native-access/jna/releases) at the moment) which provides support for currently live combinations and loses a few outdated ones, specifically:
- adds `aix-ppc64`, `darwin-aarch64`, `darwin-x86-64`, `linux-armel`, `linux-mips64el`, `linux-ppc` (32-bit), `linux-riscv64`, `linux-s390x`, and `win32-aarch64`
- removes `darwin` (replaced by `darwin-x86-64` I think), `linux-ppc64` (there is still `linux-ppc64le`), …
=> Update and unify JNA

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/main.yml, .github/workflows/plugins.yml, .github/workflows/windows.yml
An attempt for something that we discussed with @lbulej off-line.
Currently, CI using GitHub actions builds everything in one workflow. Unfortunately, unlike GitLab or Travis, one cannot restart individual jobs inside a workflow but only the whole workflow. That means that a single failing job (e.g. because SBT cannot fetch dependencies because of temporary network outage or similar) fails the whole workflow and restarting it is a very costly operation.
Therefore, this PR splits the workflow into the following parts:
* `Main` for building on latest JDK on Linux, Windows and MacOS. This also checks for encoding and coding style issues. This is meant as always-must-be-in-the-green workflow.
* `Plugins` for building and testing plugins (JDK 8 only)
* `Windows (legacy)` is a matrix build for …
=> GHA: split into more workflows

build.sbt
`finagle-chirper` and `finage-http` are not working correctly. Execution output:
> [2021-11-11T08:16:00.039+0100] com.twitter.jvm.Jvm$ (com.twitter.jvm.Jvm$ liftedTree2$1)
> WARNING: failed to create Hotspot JVM interface, using NilJvm instead
> [2021-11-11T08:16:00.397+0100] com.twitter.finagle (com.twitter.finagle.Init$ $anonfun$once$1)
> INFO: Finagle version 19.4.0 (rev=15ae0aba979a2c11ed4a71774b2e995f5df918b4) built at 20190418-114348
> Master port: 40705
> Cache ports: 44385, 41639, 35635, 43851, 39261, 40521, 36315, 36317, 37231, 46291, 33635, 33083
> ====== finagle-chirper (web) [default], iteration 0 started ======
> Resetting master, feed map size: 5000
> GC before operation: completed in 25.968 ms, heap usage 113.254 MB -> 27.470 MB.
> WARNING: This benchmark provides no result …
=> Fix: finagle-chirper and finage-http are not working correctly.

benchmarks/actors-akka/build.sbt, benchmarks/database/build.sbt, benchmarks/jdk-concurrent/build.sbt, benchmarks/jdk-streams/build.sbt, benchmarks/rx/build.sbt, benchmarks/scala-dotty/build.sbt, benchmarks/scala-sat/build.sbt, benchmarks/scala-stdlib/build.sbt, renaissance-harness/build.sbt
This is just a precursor to moving the `apache-spark` and `twitter-finagle` benchmarks to Scala 2.13.
=> Update benchmarks using Scala 2.13.6 to Scala 2.13.7

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala
Francois @farquet noticed that even though Spark 3.2.0 uses `dev.ludovic.netlib`, the old logger still pops up, so we will set the log level in both for now. Let's see if we can clean this up next Spark update.
=> Keep masking warnings from com.github.fommil.netlib

benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala, build.sbt
Updates and commonizes versions for some of the benchmark dependencies.
For **primary** dependencies that are typically unique to a benchmark module, the updated versions affects just the benchmarks in the module and if we use a newer version, some of their transitive dependencies may use a newer versions and can be shared with other modules. For example, updating the `finagle` artifacts leads to newer `zstd-jni`, which can be implicitly shared with `apache-spark`.
For secondary/transitive dependencies, the forced update applies to several benchmarks, but these are mostly support libraries. For example, we shipped 4 different versions of various `netty` artifacts, but now we ship just one, which should avoid issues such as #337.
- *`actors-akka`* benchmarks
- **`akka-actor`, 2.6.12 -> …
=> Update and commonize some of the dependencies

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/main.yml, .github/workflows/windows.yml, tools/ci/bench-standalone.sh
It exhibits a problem with `dotty` which looks like a JDK compatibility issue:
```
====> dotty
Benchmark 'dotty' failed with exception:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
at org.renaissance.scala.dotty.Dotty.setUpBeforeAll(Dotty.scala:106)
at org.renaissance.harness.ExecutionDriver.executeBenchmark(ExecutionDriver.java:82)
at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1(RenaissanceSuite.scala:163)
at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1$adapted(RenaissanceSuite.scala:159)
at …
```
=> Adding CI check for the standalone mode.

build.sbt
This is just a tiny thing but the automatic main class discovery in renaissance-core has been somewhat unreliable, so we set it explicitly to avoid producing a bundle without Main-Class attribute in the manifest.
=> Explicitly set main class in the "renaissance-core" module

benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleChirper.scala, build.sbt
The switch to Scala 2.13 apparently unearthed an issue that has been present in `finagle-chirper` all the time. The code changes in `finagle-chirper` between Renaissance 0.13 and Renaissance 0.14 were only meant to "port" it to Scala 2.13 and required changing the signature of various methods that compute feed stats to accept a `SeqView` instead of `Seq` (because in Scala 2.13, a non-strict `SeqView` is no longer a subtype of a strict `Seq`), but even in Scala 2.12, the `view` method of an `ArrayBuffer` returned a `SeqView`.
The main cause appears to be the fact that the `analyze()` method accesses an `ArrayBuffer` (representing a per-user feed) without a lock. The feed is appended to under a lock in the `Master`, but no lock is held when calculating stats on individual feeds (in a …
=> Avoid using iterator to access ArrayBuffer that can be modified during iteration

benchmarks/scala-sat/cafesat/src/main/scala/cafesat/theories/adt/AdtSolver.scala
This is just a tiny fix to use the `format()` method on the format string, because in Java 15 and later, the `formatted()` resolves to the new method in `String` which has reversed parameters. I not aware of Java 15 related bugs because of that (that particular code might not be even used), but I noticed the compiler complaining about it after the 0.14 release and it kept nagging at me. If we are to make a bugfix release, I guess we can sneak this in as well.
=> Avoid using the formatted() method in CafeSAT

benchmarks/actors-reactors/src/main/scala/org/renaissance/actors/Reactors.scala
The `PingPong` and `StreamingPingPong` sub-benchmarks use an inner class to work around the circular dependency between the `ping` and `pong` reactors. However, because reactors execute asynchronously with respect to the main thread and because the communication between the two reactors is started before the inner class is fully initialized, the `pong` reactor may actually observe an uninitialized reference (inner class instance variable) to the `ping` reactor (the `pong` reactor's event handler may start executing before the constructor of the inner class finishes). This is most likely what is going on in #359.
Because the reactor initialization mixes code executed synchronously with lambdas that capture environment but execute asynchronously (event handlers), the ordering of things is …
=> Avoid incorrect usage of partially-initialized objects in `reactors` benchmark

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/main.yml, .github/workflows/plugins.yml, .github/workflows/windows.yml, renaissance-harness/src/main/scala/org/renaissance/harness/ResultWriter.scala, tools/ci/bench-show-env.sh
No need to recursively scan all directories.
Furthermore, it seems to cause spurious errors with some runners where some of the temp directories were inaccessible.
Actually, using cache id of `{{ os }}-sbt` should be enough as the versions are handled by SBT anyway and there is no need to drop the whole cache when upgrading one package but this is probably safer.
Since GitHub allows (finally) to restart a single job, it seems better to allow all jobs to continue (even if one of them fails) as many of the failures are spurious ones anyway.
Somehow the use of `/dev/stdout` caused hard-to-explain errors on Windows runners (when executing `tools/ci/bench-show-env.sh`). Now the `ResultWriter` explicitly handles `-` to print to standard output (as is usual for many Unix utilities). As an extra …
=> GHA: various small improvements

build.sbt
Bump slf4j to version that does not ship a vulnerable log4j version (see https://www.slf4j.org/news.html). Version 1.7.36 ships with reload4j instead of the affected log4j.
This essentially prevents security scanners from flagging the renaissance benchmark suite as a security risk.
Fixes  #365
=> Bump slf4j to safe version

tools/inject-plugins.sh
Packages all files from currently built plugin targets into the harness core JAR used in the standalone mode. This simplifies plugin discovery when using `mx` in native benchmark mode.
=> Script to inject plugin classes into core JAR

benchmarks/actors-akka/src/main/resources/reference.conf, benchmarks/apache-spark/src/main/resources/log4j.properties, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala, benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleChirper.scala, benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleHttp.scala, benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleUtil.scala, build.sbt
Attempt to completely remove `log4j` from `apache-spark` dependencies. Complements #365 which updated `slf4j-log4j12` to pull in `reload4j`, but did not remove direct the Spark dependency on `log4j`.  With `log4j` removed, there seem to be some rough edges (missing appenders), probably configuration related. If this can be sorted out, we can do a minimal-change maintenance release, otherwise we'll see if the problems go away on its own after updating most of the dependencies.
=> Remove log4j dependencies

.github/workflows/main.yml
So far, images from the `docker.io/renaissancebench/buildenv` were versioned by JDK version only. That makes testing of new images impractical as there is no way to distinguish releases of the images (e.g. the image name does not reflect which Fedora version was used).
Thus pushing new version to DockerHub immediately influences how we build _any_ version of Renaissance here on GitHub CI.
The `v1-` version is a tagged version of existing images and hence the transition should be smooth.
`v2-` would come in a separate PR and would probably introduce images built on Fedora 37 and for newer JDKs too.
=> CI: use versioned image names

.github/workflows/main.yml, tools/ci/common.sh
Overall a small change for CI, mostly covered by changes in the Docker images used for the testing.
* Added JDK 20 image
* 21-ea blocked by #370 
* Use 18 and 19 releases (instead of early access builds)
* Moved to Fedora 37 as the base image
* Bypass issue with Git unsafe directory (see https://github.com/actions/checkout/issues/760)
* Not sure why the extra call is still needed though (updating to newer `actions/checkout` did not help)
There are still appearing spurious issues when building JMH image (when list of benchmarks is empty) and sometimes even some concurrent exception is raised by SBT itself. Seems that they are not caused by this change and I was unable to reproduce them locally.
=> CI: add JDK 20, test on Fedora 37

benchmarks/actors-reactors/src/main/scala/org/renaissance/actors/Reactors.scala
The leaks were in the `ForkJoinThroughput` and `Fibonacci` workloads, the former retained around a megabyte of heap data per repetition, the other was somewhat smaller.
=> Plugging reactor leaks

.github/workflows/ea-jdk.yml, .github/workflows/main.yml, tools/ci/get-latest-ea-jdk.sh
Three major changes:
* CI runs only on LTS and latest JDK
* Not JDK21-ea as we need to upgrade SBT and perhaps something else too?
* Switch to `v5` of the Docker images (new rebuilds, added OpenJ9 for 17, new Ant etc.)
* Make build on latest EA JDK on-demand only (not fully tested, these jobs can be executed only on master)
Overall, this should reduce CI time significantly while still keeping a wide range of tested JDK versions.
=> Streamline CI

.github/dependabot.yml
This setup should ensure that whenever there is a new version of some of the GitHub actions modules (e.g. the one responsible for repository checkout) a bot creates an automated pull request with the new version.
=> Use GitHub Dependabot for Actions

build.sbt, renaissance-core/src/main/java/org/renaissance/core/BenchmarkSuite.java, renaissance-harness/src/main/scala/org/renaissance/harness/RenaissanceSuite.scala
Requires a few tweaks to allow cross-compiling between Scala 2.12, 2.13 and 3.3. This is needed to enable gradual migration of (some) benchmarks to Scala 3. This is needed by a subsequent update to `dotty` to avoid incompatibility with JDK21.
=> Introduce Scala 3 variant of the harness

benchmarks/neo4j/src/main/scala/org/renaissance/neo4j/Neo4jAnalytics.scala, benchmarks/neo4j/src/main/scala/org/renaissance/neo4j/analytics/AnalyticsBenchmark.scala, build.sbt
In addition to the update, this also extracts JSON loading to a higher level (from `AnalyticsBenchmark` to `Neo4jAnalytics`) and uses `play-json` instead of `lift-json` to load JSON data. The data itself has been sanitized with respect to types and the structure has been simplified, dropping unnecessary field identifiers to simplify loading.
Also includes a bunch of cleanups to avoid Scala style violations and/or some compiler warnings.
=> Update Neo4j to version 4.4.25

build.sbt
As of now, version 22.12.0 is the most recent release. Apparently, there have been no releases in 2023.
=> Update Finagle to version 22.12.0

benchmarks/actors-akka/src/main/scala/edu/rice/habanero/actors/AkkaActor.scala, benchmarks/actors-akka/src/main/scala/edu/rice/habanero/benchmarks/uct/UctAkkaActorBenchmark.scala, benchmarks/actors-akka/src/main/scala/org/renaissance/actors/AkkaUct.scala, build.sbt
Version 2.6.17 introduced support for Scala 3. The current release of Akka is version 2.9.x, but version 2.6.x is the last under Apache License, so that's where we will stay for now. Includes a few minor cleanups for a few deprecated elements.
=> Update Akka to version 2.6.21 and migrate actors-akka to Scala 3

benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala, build.sbt
This should avoid issues with using Scala 3 code (scala3-compiler_3) from Scala 2. This broke with version 3.1.3 of scala3-compiler when Scala 2.13 compiler started to complain about "Unsupported Scala 3 union in parameter value" (3.1.2 was the last to work).
For compatibility with JDK21 (see #384), we need fixes to Tasty reader which was broken by changes to javac in JDK21-b21 (see JDK-8292275), which only made it into version 3.3.1-RC1.
Using reflection would probably fix the problem, as might a Java-based bridge method, but switching to Scala 3 seems to work as well and paves the way to introducing more Scala 3 benchmarks in the future.
Fixes #384.
=> Update scala3-compiler to version 3.3.1 and migrate scala-dotty to Scala 3

README.md, benchmarks/neo4j/src/main/scala/org/renaissance/neo4j/Neo4jAnalytics.scala
This expands the range of JVM versions supported by `neo4j-analytics` to [11,20] instead of [11,15], but JDK21 is a no-go for now (see #408).
=> Bump supported JVM in neo4j-analytics to version 20

build.sbt
Also forces a common version of Scala 2.13 `scala-library` between Scala 2 and Scala 3 benchmarks.
=> Update Scala 2 to version 2.12.18 and 2.13.12

README.md, benchmarks/database/src/main/resources/simplelogger.properties, benchmarks/database/src/main/scala/org/renaissance/database/DbShootout.scala, build.sbt, tools/ci/common.sh
Updates MapDB version from 3.0.1 to 3.0.10, H2 MVStore from version 1.4.192 to version 2.1.214, and Chronicle Map from version 3.17.0 to version 3.22.9
This makes the `db-shootout` benchmark compatible with JDK 18 (up from 11). 
Starting with JDK 19, the benchmark fails because `chronicle-core` is using reflection to look up the `sun.nio.ch.FileChannelImpl.map0(int,long,long,boolean)` method which is not available in JDK 19 anymore.
Using more recent Chronicle Map (such as 3.23.5 or even 3.24ea3) is currently not an option, because SBT fails to find their `third-party-bom`.
=> Update primary dependencies in db-shootout benchmark to improve JVM compatibility

benchmarks/jdk-concurrent/src/main/scala/org/renaissance/jdk/concurrent/FjKmeans.scala, benchmarks/jdk-concurrent/src/main/scala/org/renaissance/jdk/concurrent/FutureGenetic.scala, benchmarks/jdk-streams/src/main/scala/org/renaissance/jdk/streams/Mnemonics.scala, benchmarks/jdk-streams/src/main/scala/org/renaissance/jdk/streams/ParMnemonics.scala, benchmarks/jdk-streams/src/main/scala/org/renaissance/jdk/streams/Scrabble.scala, benchmarks/rx/src/main/scala/org/renaissance/rx/RxScrabble.scala, build.sbt, renaissance-core/src/main/java/org/renaissance/core/Launcher.java
Because we need the harness to build with Scala 3 anyway, this makes Scala 3 the default for the harness and for the Scala wrappers of Java-only benchmarks. Unlike the wrappers, the harness needs to be maintained to cross-build with older Scala versions (2.13 and 2.12) so that an appropriate harness version can be used with the standalone benchmarks.
=> Use Scala 3 version of the harness by default and in Java-only benchmarks

benchmarks/actors-reactors/reactors/build.sbt, benchmarks/actors-reactors/reactors/project/plugins.sbt
Drops cross-building and tests. Avoids import failures on conflicting dependencies when opening the project with IntelliJ IDEA. Might speed up SBT initialization by dropping cross-build plugins that produce additional projects.
=> Minimize build.sbt for the included reactors dependency

build.sbt
Also updates various common and secondary dependencies:
- database
- `jnr-posix` to version 3.1.18
- `agrona` to version 1.19.2
- common
- `commons-io` to version 2.14.0
- `netty` to version 4.1.99.Final
- harness
- `scopt` to version 4.1.0
=> Update H2 MVStore to version 2.2.224 and neo4j to version 4.4.26

benchmarks/jdk-concurrent/src/main/java/org/renaissance/jdk/concurrent/JavaKMeans.java
This ensures that all forked tasks get executed by the threads from the fork-join pool. Not doing so allows `invoke()` to start executing in the current thread, i.e., not on the (explicitly) given pool, which in turns allows subsequent `fork()` calls to schedule the forked tasks on the common pool, because the calling thread is not on the fork-join pool.
Fixes #374
=> Submit the k-means computation as a task to the fork-join pool

renaissance-jmh/wrappers/src/main/java/org/renaissance/jmh/JmhRenaissanceBenchmark.java, tools/ci/common.sh
Wraps `Benchmark` interface methods with code that set and restores the context class loader for the current thread when running with JMH. This is because JMH option `-t` causes it to create more benchmark runners that invoke the `Benchmark.run()` method concurrently on a single benchmark instance, but do not replicate the context class loader of the (initial) main thread.
Even though this is not really supported (or intended) use of the `Benchmark` interface, the benchmarks should not crash because they fail to load their classes.
One other change is that the JMH wrappers now call `setupBeforeEach()` and `tearDownAfterEach()` after each measured method invocation as they should. This probably only affects runs with timed JMH iterations, during which JMH would invoke the measured method …
=> Set/restore context class loader around benchmark methods in JMH

build.sbt
Also drops a few unused transitive dependencies. Reduces the size of the bundle.
=> Use common versions of various dependencies

benchmarks/apache-spark/src/main/resources/log4j2.xml, build.sbt
This is to improve compatibility with (more recent) IBM Semeru builds of OpenJ9-based JVMs. There was some renaming going on that resulted in changes to the contents of `java.vendor`, resulting in Hadoop 3.3.4 failing to find some classes. This was fixed in Hadoop version 3.3.5, but 3.3.6 is the most recent.
Details at https://github.com/apache/hadoop/pull/4537
=> Update Hadoop to version 3.3.6

.github/workflows/ea-jdk.yml, .github/workflows/main.yml, build.sbt, tools/ci/common.sh
This updates the CI to build on Java 21, 17, and 11, dropping Java 8. Also fixes cache configuration and uses new build environment packages that introduce testing on IBM Semeru Open builds of the OpenJ9-based JVMs.
=> CI: Build on Java 21 and drop Java 8

CONTRIBUTING.md, README.md, benchmarks/actors-reactors/reactors/build.sbt, build.sbt, project/build.scala, renaissance-harness/src/main/scala/org/renaissance/harness/MarkdownGenerator.scala, renaissance-harness/src/main/scala/org/renaissance/harness/RenaissanceSuite.scala
The core classes and the harness still targets Java 8 (for now) so that the big bundle can politely say that a benchmark is not supported when run on Java 8. This will probably go away with the next "major" update or when we start using Java 11 features (or API) in the harness.
=> Target Java 11 as the default minimal JVM for benchmarks

benchmarks/jdk-concurrent/src/main/scala/org/renaissance/jdk/concurrent/FjKmeans.scala
For each loop, computed centroids are sorted by the value of their first dimension. After sorting, every centroid position is compared with expected position of given centroid. If expected centroid positions equals to the computed centroid positions, we can validate the benchmark result.
=> Add validation to fj-kmeans benchmark

benchmarks/jdk-concurrent/src/main/java/org/renaissance/jdk/concurrent/JavaJenetics.java, benchmarks/jdk-concurrent/src/main/scala/org/renaissance/jdk/concurrent/FutureGenetic.scala
There were race conditions in the computation of future-genetic, because all threads in algorithm parallelization were using same random generator. Therefore results were not stable. Solved by creating and adding to the computation engine new instances of Alterer, Survivor Selector, Offspring selector, Genotype factory and initialized those instances with their own random generator. (Created new instances of original objects, but with unique random generator connected to it.)
Validation is done by sorting genes of result genotype by their value and comparing genes values with expected values of genes in the genotype.
=> Add validation to future-genetic benchmark

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/Als.scala
The trained ALS model can be represented as a 2-dimensional matrix of features and the validation checks the shape and the content of the matrix. Regarding the content, it compares the sum and sum of squares of all matrix values with expected values.
The validation does not change the code that is being measured and should not really impact benchmark performance. As a quick check, I calculated an average duration from the last 5 repetitions of a single run of the benchmark before and after validation:
- without validation: 2235,345ms
([als.no-validation.result.txt](https://github.com/renaissance-benchmarks/renaissance/files/14229213/als.no-validation.result.txt))
- with validation: 2323,872ms
([als.with-validation.result.txt](https://github.com/renaissance-benchmarks/renaissance/files/1422 …
=> Add validation to als benchmark

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala
Validation currently supports only binary classification which returns a single intercept value. If multinomial logistic regression is needed, the validation needs to be updated to support multiple intercept values.
The validation checks logistic regression model's coefficients, intercept, and the number of classes the model can classify. For the coefficients, it compares the sum and sum of squares of all coefficient values with the expected values, and then validates the coefficient count. Regarding the intercept, its value is compared with the expected value, and then the validation checks that the model contains only one intercept.
The validation does not change the code that is being measured and should not really impact benchmark performance. As a quick check, I calculated an average …
=> Add validation to log-regression benchmark

CONTRIBUTING.md
Remove the shell prefix so that the user can just click the copy icon and paste the command.
=> docs: remove shell prefix in CONTRIBUTING.md

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/MovieLens.scala
The benchmark originally returned an empty set of recommended movies due to passing a userID of value 0 to the predict method. User ID 0 is undefined (as the model was not trained with ratings from this user), causing the predict method to return an empty set. This issue was resolved by retrieving the userID from the 'ratings-personal.csv' file.
The validation process involves two steps. First, it checks whether the specified number of top recommended movies contains a defined set of expected movies. Next, the validation compares the Root Mean Square Error (RMSE) achieved by the best model on the validation subset with the expected value.
The validation does not change the code that is being measured to a greater extent and thus should not really impact benchmark performance. As a quick …
=> Add validation to movie-lens benchmark

benchmarks/scala-stm/src/main/scala/org/renaissance/scala/stm/Philosophers.scala, benchmarks/scala-stm/src/main/scala/org/renaissance/scala/stm/ScalaStmBench7.scala, benchmarks/scala-stm/src/main/scala/stmbench7/scalastm/ImmutableSeqImpl.scala, benchmarks/scala-stm/src/main/scala/stmbench7/scalastm/ImmutableSetImpl.scala, benchmarks/scala-stm/src/main/scala/stmbench7/scalastm/IndexImpl.scala, benchmarks/scala-stm/src/main/scala/stmbench7/scalastm/LargeSetImpl.scala, benchmarks/scala-stm/src/main/scala/stmbench7/scalastm/ScalaSTMInitializer.scala, benchmarks/scala-stm/stmbench7/src/main/java/stmbench7/Benchmark.java, build.sbt
Migrates the `scala-stm` benchmarks to Scala 3 (skipping Scala 2.13), leaving only the `reactors` benchmark to be migrated to at least Scala 2.13 (#324).
Below are plots from simple measurements I collected from 15 runs (150 repetitions each) using JDK 11 (default settings) on 8 cores of Xeon E5-2697A v4:
- the `scala212` variant corresponds to commit 87358d9 (Renaissance 0.15.0, scala-stm 0.8 with Scala 2.12.18)
- the `scala3_stm` variant corresponds to commit 6d1cb1f (scala-stm 0.11.1 with Scala 3.3.1)
=> Migrate scala-stm benchmarks from Scala 2.12 to Scala 3

benchmarks/scala-stm/src/main/scala/org/renaissance/scala/stm/Philosophers.scala, benchmarks/scala-stm/src/main/scala/org/renaissance/scala/stm/RealityShowPhilosophers.scala
This started as a simple hash-based validation @BohdanQQ's [fork](https://github.com/BohdanQQ/renaissance/tree/benchmark/philosophers/validation) from which I cherry-picked bits. Because there is no reason to validate hash of the output when we have the actual values, I modified the validation to validate the number of meals eaten directly and added an extra check that the forks have no owner at the end.
=> Add simple validation to the philosophers benchmark

benchmarks/scala-stm/src/main/scala/org/renaissance/scala/stm/Philosophers.scala, benchmarks/scala-stm/src/main/scala/org/renaissance/scala/stm/RealityShowPhilosophers.scala
This includes two related changes and one extra bit.
The first reduces the duration of the transaction building the "image of the scene". Previously the image was being built inside the transaction, making the transaction last unnecessarily longer. Now we only take a snapshot of the state within the transaction and build the image outside the transaction to avoid blocking philosopher threads.
The second change makes the number of scans constant for a given workload. Previously, camera scans were triggered in reference to wall clock time, resulting in variable number of scans during each repetition. Now the camera scans are requested based on thread progress. To keep the number of camera scans constant, the requests are counted to avoid potential loss of wake-ups when the rate of progress …
=> Make the number of "camera scans" constant in the philosophers benchmark

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/GaussMix.scala
The benchmark computation was originally unstable due to the method of generating training data points. The benchmark generated random points such that each dimension of each point was a random double between zero and one, rounded to one decimal place. This approach resulted in points representing random noise within a cuboid defined by [0, 0, ..., 0] and [1, 1, ..., 1], rather than Gaussian distributions. Additionally, the Spark GMM model fitting returns inconsistent results when different thread counts are used, making it impossible to achieve benchmark stability even with a fixed seed for the random generator.
Currently, the benchmark generates input data points grouped into clusters. These clusters are positioned with increasing offset from the vertices of a hypercube. To enhance …
=> Add gauss-mix validation

.github/workflows/ea-jdk.yml, .github/workflows/main.yml, build.sbt, project/build.sbt, project/hadoop.scala, tools/ci/common.sh
Uses ASM to patch the `UserGroupInformation` class at build time and stores it in a version-specific directory of a newly created multi-release jar, where it will be picked up by Java 23+.
This is a temporary solution, but it may be a long-term temporary solution.
Fixes #439.
=> Patch Hadoop Client API jar to avoid deprecated Java Security API

.github/workflows/main.yml
Trying how the build times would be changed if we would built Renaissance just once and then pass the pre-built JAR across multiple jobs running it.
=> CI: build once, run on multiple JDKs

benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/MovieLens.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/ResourceUtil.scala, benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala
Use the Spark DataFrameReader to load the CSV files with movies and ratings to correctly load CSV files with quoted values. Specifically, `movies.csv` was loaded "by hand"  with splitting on coma, resulting in some movie titles being cut off and part of the movie title ending up in the "genres" field, but no harm was done, because the genres are not being used by the benchmark. Anyway, it also avoids the extra IO of copying the resource files to the scratch directory.
Given the above changes, the data initialization was made more localized to avoid keeping data that are not needed for benchmark execution after the initial setup.
Because the data are loaded using the `DataFrameReader` from Spark Session instead of the `textfile()` function from Spark Context (which uses `hadoopFile()` …
=> Use Spark to load CSV files and avoid extra IO

README.md, benchmarks/database/src/main/resources/simplelogger.properties, benchmarks/database/src/main/scala/org/renaissance/database/DbShootout.scala, benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala, build.sbt, tools/ci/common.sh
Updates Scala, primary benchmark dependencies and a number of secondary dependencies. Partially builds on top of #443 (which it supersedes) and goes a bit further where possible. The `db-shootout` benchmark is now compatible with JDK upto 22 (interestingly, in standalone mode, it can actually run even on Java 24). This should bring us close to release.
Scala updates
- Scala 2.12 updated to `2.12.20`
- Scala 2.13 updated to `2.13.15`
- Scala 3 updated to `3.3.4`
Updates in `apache-spark`
- Spark updated from `3.5.0` to `3.5.3`
- Secondary dependencies
- Arrow updated to `18.0.0`
- Parquet updated to `1.14.3`
- Netty updated to `4.1.114.Final`
- Guava updated to `33.3.1-jre`
Updates in `db-shootout`
- `agrona` updated from `1.19.2` to `1.22.0` (later versions require Java 17)
- `mapdb` …
=> Update benchmark dependencies

.github/workflows/ea-jdk.yml, .github/workflows/main.yml
Image update to Fedora 41 done in renaissance-benchmarks/docker-buildenv#29.
=> CI: update images to v14

benchmarks/actors-akka/src/main/resources/reference.conf
Configures default logging levels, disables framework exit on fatal error (harness should do it) and disables JVM shutdown hooks (benchmark should handle it). The idea is that benchmark should not register global hooks that run outside the harness control. The benchmark appears to terminate the actor system properly, so there should be no need for Akka to do this.
=> Update Akka configuration to avoid registering JVM shutdown hooks and calling system exit on fatal error

tools/ci/bench-base.sh, tools/ci/bench-standalone.sh, tools/ci/common.sh
To debug #457 we could run each Java process in `timeout` that first sends `SIGQUIT` (`3`) which tells the JVM to dump all threads (thanks @ceresek for the suggestion) and then kills the process anyway.
This also shortens the execution time for failing jobs as `gauss-mix` is killed after 5 minutes instead of eating the maximum job time (30m).
This works on both Linux and Windows (I am not sure if the signal is somehow emulated as I have not seen it fail there yet but it does not fail anything on good runs), on MacOS the command is not installed but majority of the failures were on Linux anyway.
Already we have one instance of failure here: https://github.com/renaissance-benchmarks/renaissance/actions/runs/11932162022/job/33256738789?pr=462#step:9:397
=> CI: thread dump on benchmark timeout

README.md, benchmarks/database/src/main/scala/org/renaissance/database/DbShootout.scala
Chronicle needs the `java.class.path` property to contain certain jars because it is using the Java compiler to compile generated source code and expects the compiler to find libraries through the normal class path lookup. It is enough to set the property during initialization.
On Java 22 and lower, some code actually sets the `java.class.path` property to the contents of the URL class loader, but it does not happen on Java 23 and later. So we do it explicitly.
This makes `db-shootout` compatible with Java 23 and 24-ea both in standalone and harness mode.
Closes #458.
=> Set 'java.class.path' temporarily during Chronicle intialization

benchmarks/jdk-concurrent/src/main/java/org/renaissance/jdk/concurrent/JavaJenetics.java, benchmarks/jdk-concurrent/src/main/scala/org/renaissance/jdk/concurrent/FutureGenetic.scala
Renamed chromosome_count to population_size to better reflect its role. The benchmark generates a population of 50 genotypes, each containing a single chromosome with 200 double Genes. Evolution is computed for the population, and at the end, the best genotype is selected, and its chromosome is returned. Since the term chromosome_count=50 was misleading, this change improves clarity.
Renamed chromosomeRandom to genotypeRandom, as this random generator is responsible for creating new random genotypes, not chromosomes.
=> Refactor parameter and variable names for clarity in the future-genetic benchmark

renaissance-core/src/main/java/org/renaissance/core/BenchmarkSuite.java, renaissance-core/src/main/java/org/renaissance/core/Cleaner.java, renaissance-core/src/main/java/org/renaissance/core/DirUtils.java, renaissance-core/src/main/java/org/renaissance/core/Logging.java, renaissance-core/src/main/java/org/renaissance/core/ModuleLoader.java
This ensures that library JAR files stored in the launcher and harness scratch directories are closed before removing the scratch
directory roots. This was a problem on NFS, where the open files could not be unlinked from the directory (NFS kept around `.nfs*` temporaries), preventing the removal of the directories.
Also fixes the logging setup which used `StreamHandler` instead of `ConsoleHandler` for `stderr`, which resulted in closing of the `stderr` as a result of running the `java.util.logging` shutdown hook, effectively gagging `stderr`.
Closes #464
=> Close URLClassLoader instances to enable proper cleanup on NFS

renaissance-core/src/main/java/org/renaissance/BenchmarkParameter.java, renaissance-harness/src/main/scala/org/renaissance/harness/RenaissanceSuite.scala, renaissance-harness/src/main/scala/org/renaissance/harness/ResultWriter.scala
The value is stored as `vm_start_ns` in the CSV output and `vm.start_ns` in the JSON output. It has no official semantics (unlike `vm_start_unix_ms`), but allows recovering the `nanoTime()` value associated with the `vm_start_unix_ms` value. It also bumps the JSON format version to 6.
BTW, only the last commit is the important one, the others are things that I had lying around for quite some time and thought to sneak them in.
Closes #468
=> Add VM start in terms of nanoTime() to the CSV and JSON outputs
