- website/_layouts/mainrenaissance.html
- website/resources/styles/proj.css
Sorry, wrong use of revert and merge, should be OK now.
> Website stripe plot

- CONTRIBUTION.md
- renaissance-harness/src/main/scala/org/renaissance/renaissance-suite.scala
- website/index.md
- Update CONTRIBUTION.md to remove unicode characters since they do not render correctly on the website
- Update main page title
> Minor website changes

- renaissance-harness/src/main/scala/org/renaissance/renaissance-suite.scala
As long as the shutdown hook (from `Runtime` class) is called this should work quite fine.
Added extra field to JSON output to mark VM termination kind.
> Store JSON and CSV on Ctrl-C (fixes #119)

- build.sbt
> Add JMH default values for iteration count that correspond more closely to Renaissance defaults.

- benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala
I have tried the suggestion from #176 discussion but that does not work as Dotty looks at the root classpath, not at the current class loader.
I have added an explanation to the source and provided a fix that converts the URLs to local file paths which should work well even on Windows.
> dotty: rework classpath handling (fixes #176)

- .travis.yml
Only added the `-foe` option to report failure via exit code.
> JMH on Travis: fail on error (fixes #199)

- website/resources/styles/proj.css
This is a part of the solution to the current website issue.
> Introduce a new CSS class for the rightmost li element of the website.

- benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/LogRegression.scala
- benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/MovieLens.scala
- benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/SparkUtil.scala
Fixing checkstyle issues introduced in #228.
That's what happens when we don't look at the Travis CI results...
> Checkstyle fix

- renaissance-core/src/main/java/org/renaissance/core/BenchmarkSuite.java
- renaissance-core/src/main/java/org/renaissance/core/ModuleLoader.java
- renaissance-harness/src/main/scala/org/renaissance/harness/ConfigParser.scala
- renaissance-harness/src/main/scala/org/renaissance/harness/RenaissanceSuite.scala
> Fix plugin loading

- .github/workflows/build.yml
- plugins/ubench-agent/build-ubench-agent.sh
- tools/ci/bench-plugins.sh
- tools/ci/build-plugins.sh
- tools/ci/common.sh
Ensure we build our plugins regularly too.
> CI: test with plugins too

- website/_posts/2021-07-07-renaissance-0-12-0.md
This should be the last thing to go in before we tag the next release. Feel free to suggest additions to the release notes.
> Release announcement for version 0.12.0

- renaissance-core/src/main/java/org/renaissance/core/BenchmarkSuite.java
- renaissance-core/src/main/java/org/renaissance/core/ModuleLoader.java
- renaissance-harness/src/main/scala/org/renaissance/harness/RenaissanceSuite.scala
A follow up to the discussion in #292.
@lbulej Have you meant something like this?
> Module loading refactoring

- documentation/README.md
- documentation/making-release.md
... so that people don't have to re-discover it on their own with every release...
> Add a description of the release process

- benchmarks/twitter-finagle/build.sbt
- benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleChirper.scala
These are just the necessary updates. I have a bunch of other cleanups slated for another PR.
> Update twitter-finagle benchmarks to use Finagle 21.10.0 and Scala 2.13.7

- project/plugins.sbt
This should pull in newer JMH which should make it easier to get perfasm to work on ARM. Fixes #329.
> Bump sbt-jmh to version 0.4.3

- benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala
In standalone mode (without modules), even if the current class loader is a URLClassLoader (which it is on JDK8 but not on JDK11), it may not provide enough information about the real class path. For example, on JDK8, the class loader returns a single URL representing the jar file passed to 'java -jar', which is no different from the value of the 'java.class.path' system property.
So we instead try to detect if the benchmark is running in standalone mode and if yes, we build the class path using the 'Class-Path' attribute in the jar manifest. If this fails, we try to get class path URLs from the class loader, and in the worst case fall back to the current class path, which should help in situations where we try to run the benchmark completely manually, with all jar files listed on the …
> Fix standalone mode for Dotty

- benchmarks/scala-dotty/src/main/scala/org/renaissance/scala/dotty/Dotty.scala
Even though there is only a single jar on the class path, the class loader actually knows about all referenced jars and can search them for resources. Depending on the order in which the class loader searched the jars, we might get manifest from different jar instead of the one we are looking for. The fact that it was working so far was just luck. With newer JDKs, the primary jar (the only one on the explicit class path) was searched first, while on JDK8 it was not the case, so we were looking for the 'Class-Path' attribute in the wrong manifest.
Really fixes #347
> Standalone mode: load manifest directly from jar, not as a resource

- benchmarks/twitter-finagle/src/main/scala/org/renaissance/twitter/finagle/FinagleChirper.scala
This is a follow up to #356 and provides an alternative fix to #354 (and #345) that should be compatible with the Java memory model. Here we use a `FeedBuffer` class derived from `mutable.ArrayBuffer` to store the feed strings. The derived class provides a `snapshotView()` method that creates a snapshot view of the underlying array (instead of the buffer). This ensures that even if the buffer is appended to (and the underlying array is replaced), we can still iterate over the original contents. This works under the assumption that the feed represented by the buffer is only appended to.
The `snapshotView()` method is called under the same lock that is used to modify the buffer contents and we don't need to worry about the underlying array reference being changed during the iteration. Let …
> Iterate over a snapshot of the ArrayBuffer internals

- benchmarks/jdk-concurrent/src/main/java/org/renaissance/jdk/concurrent/JavaJenetics.java
- build.sbt
Mostly harmless updates related to `future-genetic` and the Jenetics library, removing usage of some deprecated methods and sketching update path.
> Minor cleanups in future-genetic

- benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/Als.scala
Some many-core architectures appear to accumulate a little bit more error in the sums of user (or possibly) item factors.
This doubles the tolerance for the user factors and makes the tolerances configurable to facilitate workarounds (if necessary).
Closes #478.
> Bump validation tolerance for 'als' and expose it through parameters
